knp_paginator:
    page_range: 5            # Nombre de pages affichées dans la pagination
    default_options:
        page_name: page      # Nom du paramètre GET pour la pagination
        sort_field_name: sort # Nom du paramètre GET pour le tri
        sort_direction_name: direction # Nom du paramètre GET pour la direction du tri
        distinct: true       # Assure que les résultats paginés sont distincts
    template:
        pagination: '@KnpPaginator/Pagination/sliding.html.twig' # Template utilisé pour la pagination
        sortable: '@KnpPaginator/Pagination/sortable_link.html.twig' # Template utilisé pour les liens triables
